@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxODc1YjkyZC02NzU2LTRjYjUtOWVlMy0wZmExZjI1NWE4YmQiLCJqdGkiOiIxODc1YjkyZC02NzU2LTRjYjUtOWVlMy0wZmExZjI1NWE4YmQiLCJ1c3IiOjMsInN1YiI6IjMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NzMzOTk5ODUsImV4cCI6MTc3NDAwNDc4NX0.YZf-cEEWu5WYT4cNcbU69o51v9Lk_VEgR7OZLruoQ7o

### Credentials
GET http://localhost:3000/api/me/credentials.json
Authorization: {{ token }}


### Credential
GET http://localhost:3000/api/me/credentials/1.json
Authorization: {{ token }}


### Change credential password
PUT http://localhost:3000/api/me/credentials/1.json
Authorization: {{ token }}
Content-Type: application/json

{ "credential":
  {
    "password": "changed!!"
  }
}