@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1MWFjNjAxMy03NzA0LTQzZTUtODA4OS0yZGFjNWU0MWUwZDgiLCJqdGkiOiI1MWFjNjAxMy03NzA0LTQzZTUtODA4OS0yZGFjNWU0MWUwZDgiLCJ1c3IiOjgsInN1YiI6IjgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NzQyOTQwNDgsImV4cCI6MTc3NDg5ODg0OH0.N9OXQYo-OL9a6BWnQ8tYLHe-yF3Io4qXY3IQn-GlqK8


### Credentials
GET http://localhost:3000/api/me/credentials.json
Authorization: {{ token }}


### Credential
GET http://localhost:3000/api/me/credentials/1.json
Authorization: {{ token }}


### Create credential
POST http://localhost:3000/api/me/credentials.json
Authorization: {{ token }}
Content-Type: application/json

{ "credential":
  {
    "name": "http_test",
    "web_id": 5
  }
}


### Change credential password
PUT http://localhost:3000/api/me/credentials/1.json
Authorization: {{ token }}
Content-Type: application/json

{ "credential":
  {
    "password": "changed!!"
  }
}