@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmMmI1ZTAxMC02ZmE2LTQwNjYtODM1OC0yZWU3NDNmNGEyOGQiLCJqdGkiOiJmMmI1ZTAxMC02ZmE2LTQwNjYtODM1OC0yZWU3NDNmNGEyOGQiLCJ1c3IiOjIsInN1YiI6IjIiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NzQyODc3MDMsImV4cCI6MTc3NDg5MjUwM30._-BNbTAG2EUVnWXpOQVYCkWjaAVky28WEgH4MwnW8kM

### Web companies
GET http://localhost:3000/api/me/web_companies.json
Authorization: {{ token }}


### Webs
GET http://localhost:3000/api/me/webs.json
Authorization: {{ token }}
